FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src 

# Copy and restore Api project
COPY Api/*.csproj Api/
RUN dotnet restore Api/Api.csproj

# Copy the remaining code
COPY Api/ Api/
COPY IdentityService/DomainConstants*.cs IdentityService/

RUN dotnet publish Api/Api.csproj -c Release -o /app

# Phase #2, Build final image 

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS release

WORKDIR /app

COPY --from=build /app .

EXPOSE 80

ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "./Api.dll"]
