FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

# Copy and restore BackendApiHost project
COPY JsBffSample/BackendApiHost/*.csproj JsBffSample/BackendApiHost/
RUN dotnet restore JsBffSample/BackendApiHost/BackendApiHost.csproj

# Copy the remaining code
COPY JsBffSample/BackendApiHost/ JsBffSample/BackendApiHost/
COPY IdentityService/DomainConstants*.cs IdentityService/

RUN dotnet publish JsBffSample/BackendApiHost/BackendApiHost.csproj -c Release -o /app

# Phase #2, Build final image

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS release

WORKDIR /app

COPY --from=build /app .

EXPOSE 80 443

ENV ASPNETCORE_URLS=http://+:80;https://+:443

ENTRYPOINT ["dotnet", "./BackendApiHost.dll"]
